---
name: 'Lint Only'

on: # yamllint disable-line rule:truthy
  workflow_dispatch: {}

jobs:
  lint:
    name: 'Call Lint from Template'
    uses: rjrpaz/ansible-collection-template/.github/workflows/lint-only.yml@split-workflows