---
name: 'Release'

on: # yamllint disable-line rule:truthy
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  release:
    name: 'Call Release from Template'
    uses: rjrpaz/ansible-collection-template/.github/workflows/release.yml@main
    secrets: inherit