---
name: 'Test Only'

on: # yamllint disable-line rule:truthy
  workflow_dispatch: {}

jobs:
  test:
    name: 'Call Test from Template'
    uses: rjrpaz/ansible-collection-template/.github/workflows/test-only.yml@split-workflows